### ISSUE TITLE
Crashes if I reduce the classes

### ISSUE THREAD

**Issue by raghavzns** [Qengineering/YoloFastest-ncnn-Jetson-Nano#4]
Hi Sir,
I removed all class names from mainFV2.cpp, and kept just single class "person". Rebuilt and ran the code, but it crashes after running for a few seconds. 
Why Im doing this : I just want to detect person in my video feeds, hence I thought removing all other classes might speed up the inference a little bit.

**Comment by Qengineering** [comment]
That's not the way. 
Your deep learning model still detects all 80 classes mentioned in the `class_names` structure. 
Hence, when a car is detected (item 3) and your `class_names` has no entry '3' any more, it errors.
If you only want to detect a person, check your `std::vector<TargetBox>& boxes` list (see line 46 `draw_objects` where the software iterates through the list)
